"use client"

import { PDFForm } from "@/components/pdf-form"
import jsPDF from "jspdf"
import html2canvas from "html2canvas"

export default function FormPage() {
  const handleDownloadPDF = async () => {
    const element = document.getElementById("form-content")
    if (!element) return

    // Show loading message (optional)
    const originalButtonText = document.getElementById("download-btn")?.innerHTML
    if (originalButtonText) {
      document.getElementById("download-btn")!.innerHTML = "Generating PDF..."
    }

    // Wait for canvas to render
    const canvas = await html2canvas(element, {
      scale: 2, // Higher scale = better quality PDF
      useCORS: true, // Enable CORS if your form uses external images
    })

    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF("p", "mm", "a4")

    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width

    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight)

    // Optional: add a header (example)
    pdf.setFontSize(12)
    pdf.text("Generated by NextPhase IT Client Intake Form", 14, pdf.internal.pageSize.getHeight() - 10)

    pdf.save(`client-intake-form_${new Date().toISOString().slice(0,10)}.pdf`)

    // Reset button text
    if (originalButtonText) {
      document.getElementById("download-btn")!.innerHTML = originalButtonText
    }
  }

  return (
    <div className="min-h-screen bg-gray-100 py-8">
      <div className="container mx-auto px-4">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">NextPhase IT Client Intake Form</h1>
          <p className="text-gray-600">Print this page or download the completed PDF form</p>
          <div className="mt-4 space-x-4">
            <button
              onClick={() => window.print()}
              className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors"
            >
              Print Form
            </button>

            <button
              id="download-btn"
              onClick={handleDownloadPDF}
              className="bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 transition-colors"
            >
              Download PDF
            </button>
          </div>
        </div>

        {/* Wrap the form content to capture */}
        <div
          id="form-content"
          className="bg-white p-6 rounded-lg shadow-md border border-gray-300"
        >
          <PDFForm />
        </div>
      </div>
    </div>
  )
}
